name: kal_rasol_allah
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  arabic_font: ^0.0.9
  cupertino_icons: ^1.0.8
  dots_indicator: ^4.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_calendar_carousel: ^2.5.4
  flutter_svg: ^2.2.4
  gap: ^3.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

# ✅ إعدادات الأيقونة
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/consts/logo.png"

  # 🔥 (اختياري بس مهم عشان شكل احترافي على Android)
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/consts/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/consts/
